branchName: '${issue.number}'
branches:
  - label: '🚨 critical'
    prefix: 'hotfix/'

  - label: '*'
    prefix: 'feature/'
commentMessage: '🌱 브랜치 ${branchName} 생성 완료!
openDraftPR: false
autoCloseIssue: true
copyIssueLabelsToPR: true
copyIssueAssigneeToPR: true
copyIssueMilestoneToPR: true