language: "ko"        # 2글자 코드
early_access: false

reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: false
  poem: false
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false

  path_instructions:
    - path: "src/main/java/**/*.java"
      instructions: "SOLID 원칙, 스프링 어노테이션, 의존성 주입 패턴, 예외 처리에 중점을 둔다"
    - path: "src/test/**/*.java"
      instructions: "테스트 커버리지, 스프링 테스트 어노테이션, mock 사용법, 네이밍 규칙을 확인한다"
    - path: "**/*.{yml,yaml,properties}"
      instructions: "스프링 설정, 보안 설정, DB 연결, 환경 설정을 검증한다"

  path_filters:
    - "!**/build/**"
    - "!**/.gradle/**"
    - "!**/gradle/wrapper/**"
    - "!**/gradlew*"
    - "!**/out/**"
    - "!**/*.class"
    - "!**/*.jar"
    - "!**/*.war"
    - "!**/node_modules/**"

chat:
  auto_reply: true

tone_instructions: "
  ## 기본 규칙
  - 코드의 잠재적인 버그나 성능 문제를 찾아주세요.
  - 스프링 모범 사례, SOLID 원칙에 맞게 개선할 점이 있다면 제안해 주세요.
  - 성능 최적화가 가능한 로직이 존재한다면 알려주세요.
  - 클린 코드 원칙에 따라 개선할 점이 있다면 제안해 주세요.
  - 변경 사항을 요약해서 설명해 주세요.
  - 코드가 업데이트 되었을 때 클로드 코드로 작성된 이전 리뷰와 다른 내용을 작성해 주세요.
  
  ## !!절대 규칙
  - 절대 허구의 정보를 만들어내지 마세요.
  - 컨텍스트 또는 결과로 정확한 응답이 불가능하면 추측을 금지합니다.
"

knowledge_base:
  opt_out: false
  learnings:
    scope: auto
  issues:
    scope: auto
