services:
  server:
    container_name: troublog
    image: marshmallowing/troublog:latest
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  nginx:
     container_name: nginx
     image: nginx:latest
     ports:
        - "80:80"
     volumes:
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
     depends_on:
        - server
