server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Troublog 애플리케이션 로그
  - job_name: troublog-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: troublog-backend
          __path__: /var/log/troublog/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            thread: thread
            logger: logger
            message: message
            exception: exception
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          thread:
          logger:

  # Spring Boot 액추에이터 로그 (선택사항)
  - job_name: troublog-access-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: troublog-access
          __path__: /var/log/troublog/access.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\S+\s+\S+)\s+(?P<level>\S+)\s+(?P<message>.*)$'
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          level: