# 로컬환경입니다. application-local.yml
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

# Actuator 모니터링 설정 (Local)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always  # Local: 항상 상세정보 노출
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
    tags:
      application: ${spring.application.name}
      environment: local

# 로그 설정 (Local)
logging:
  level:
    troublog.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: DEBUG
  pattern:
    file: "%d{ISO8601} [%thread] %-5level %logger{36} - %msg%n"
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/troublog.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 7
      total-size-cap: 500MB