# 로컬환경입니다. application-local.yml
spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
    open-in-view: false
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    web: debug