global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Troublog Spring Boot 애플리케이션
  - job_name: 'troublog-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['host.docker.internal:8080']  # 로컬에서 실행되는 Spring Boot 앱
    scrape_timeout: 10s

  # Grafana 모니터링 (선택사항)
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # Loki 모니터링 (선택사항)
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']