name: CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.yml files
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml
          echo "${{ secrets.APPLICATION_PROD_YML }}" > src/main/resources/application-prod.yml
        shell: bash

      - name: Make .env file
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env
        shell: bash

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Write SSH private key to file
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Copy docker-compose.yml to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: private_key.pem
          port: 22
          source: "docker-compose.yml"
          target: "/home/ubuntu/troublog/"

      - name: Copy .env to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: private_key.pem
          port: 22
          source: ".env"
          target: "/home/ubuntu/troublog/"

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # EC2 퍼블릭 IPv4
          username: ${{ secrets.SSH_USERNAME }} # ubuntu
          key_path: private_key.pem
          port: 22
          # docker-compose가 있는 디렉토리로 이동
          script: |
            cd /home/ubuntu/troublog
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker-compose pull       # 새 이미지 받기
            sudo docker-compose down || true  # 컨테이너 종료
            sudo docker-compose up -d # 재실행
            sudo docker image prune -f # 안 쓰는 이미지 정리